HamiltonianType = "Wannier90" # OpenMX, OpenMXWannier, Wannier90
spintype = "co_spin" #Set Spin type, para, co_spin, nc_spin
result_file = ["wannier","wannier"]
atom12 = [[1,1]]



[wannier_optional]
# atom position info dose not exists at OpenMX wannier
atomnum = 2
atompos = [[0.5000000000000000,   0.5000000000000000,   0.5000000000000000],     # Atom 1 position x,y,z (fractional)
           [0.0000000000000000,   0.0000000000000000,   0.0000000000000000]        # Atom 2 position x,y,z (fractional)
           ]  # Atom 12 position x,y,z (fractional)

atoms_orbitals_list = [[1,2,3,4,5,6,7,8,9], # Atom 1 orbitals
		       [10,11,12,13]                   # Atom 2 orbitals
                      ]                     # Atom 4 orbitals




[DMFT_Jx]
Calcualtion_mode = "DMFT" # DMFT, Jx-DMFT, Jx0, Magnon are possible

DMFT_loop_N = 50

KgridNum = [8,8,8]
RgridNum = [8,8,8]
iWgridCut = 300  # It's recommended to set a value larger than 5 times of Solver_green_Cut
Solver_green_Cut = 10

Temperature = 300  # kelvin
mpi_prefix = "mpirun -np 56"
Corr_atom_Ind = [1]
Corr_orbital_Ind = [ [5,6,7,8,9] ] # orbital order = wannier orbital order
Corr_atom_equiv = [1] # start from 1, minus sign means AFM, max(Corr_atom_equiv) = # of impurity problems 

DMFT_Spin_type = 1 # 1: paramagnetic, 2 : spin-polarized


EDMFTF_MonteCar_step = 10000000
EDMFTF_warmup_step = 500000
EDMFTF_GlobalFlip = 500000
EDMFTF_tsample = 30
EDMFTF_nom = 100

compute_EF = false

Mix_selfE  = 0.5 # The portion of Old selfenergy in the mixing
basis_transform = "false"
smth_step = 0

DMFT_solver = "EDMFTF_ctqmc"  # ComCTQMC, EDMFTF_ctqmc are possible
imp1_U = 7.0
imp1_J = 0.9
imp1_dc = 8.0
imp1_int_parameterisation = "slater-condon"
imp1_int_type = "ising"
imp1_block = [[1, 0, 0, 0, 0],
              [0, 1, 0, 0, 0],
              [0, 0, 2, 0, 0],
              [0, 0, 0, 1, 0],
              [0, 0, 0, 0, 2]]

